"""db-transactor server — single-process DuckDB transaction manager.

Runs as a long-lived subprocess, accepting ``vgi_rpc`` connections over a
Unix domain socket. Owns a single DuckDB connection and serializes all
operations through it.

Usage::

    vgi-transactor --db-path /path/to/store.duckdb --socket /tmp/vgi-transactor.sock

"""

from __future__ import annotations

import argparse
import logging
import sys
import threading

import duckdb
import pyarrow as pa
from vgi_rpc import AnnotatedBatch, OutputCollector, RpcServer
from vgi_rpc.rpc import CallContext, ExchangeState, ProducerState, Stream, serve_unix

from vgi.transactor.protocol import TransactorProtocol

logger = logging.getLogger("vgi.transactor")

_COUNT_SCHEMA = pa.schema([("count", pa.int64())])


class TransactorImpl:
    """Implementation of the TransactorProtocol backed by a single DuckDB connection.

    All operations are serialized via a threading lock. Only one transaction
    can be active at a time (matching DuckDB's single-writer model).
    """

    def __init__(self, db_path: str) -> None:
        """Open DuckDB connection and initialize."""
        self._db_path = db_path
        self._conn = duckdb.connect(db_path)
        self._lock = threading.Lock()
        self._active_tx: bytes | None = None
        self._tx_condition = threading.Condition(self._lock)
        logger.info("Transactor started: %s", db_path)

    # ========== Helpers ==========

    def _table_schema(self, qualified_name: str) -> pa.Schema:
        """Get the Arrow schema for a table (excluding row_id)."""
        with self._lock:
            result = self._conn.execute(f"SELECT * FROM {qualified_name} LIMIT 0")  # noqa: S608
            return result.fetch_arrow_table().schema

    # ========== Transaction lifecycle ==========

    def begin(self, tx_id: bytes) -> None:
        """Begin a transaction."""
        with self._tx_condition:
            while self._active_tx is not None:
                logger.debug("Waiting for active transaction to complete")
                self._tx_condition.wait()
            self._active_tx = tx_id
            self._conn.begin()
            logger.info("Transaction begun: %s", tx_id.hex())

    def commit(self, tx_id: bytes) -> None:
        """Commit the active transaction."""
        with self._tx_condition:
            if self._active_tx != tx_id:
                msg = f"Cannot commit: transaction {tx_id.hex()} is not active"
                raise ValueError(msg)
            self._conn.commit()
            self._active_tx = None
            self._tx_condition.notify_all()
            logger.info("Transaction committed: %s", tx_id.hex())

    def rollback(self, tx_id: bytes) -> None:
        """Rollback the active transaction."""
        with self._tx_condition:
            if self._active_tx != tx_id:
                msg = f"Cannot rollback: transaction {tx_id.hex()} is not active"
                raise ValueError(msg)
            self._conn.rollback()
            self._active_tx = None
            self._tx_condition.notify_all()
            logger.info("Transaction rolled back: %s", tx_id.hex())

    # ========== Write operations (streaming exchange) ==========

    def insert(
        self,
        tx_id: bytes,
        schema_name: str,
        table_name: str,
        returning: bool = False,
    ) -> Stream:
        """Create an insert exchange stream."""
        qualified = f"{schema_name}.{table_name}" if schema_name else table_name
        table_schema = self._table_schema(qualified)

        # Input schema excludes row_id (auto-generated by DuckDB DEFAULT)
        input_fields = [f for f in table_schema if f.name != "row_id"]
        input_schema = pa.schema(input_fields)

        # Output schema for RETURNING also excludes row_id
        output_schema = input_schema if returning else _COUNT_SCHEMA

        state = _InsertState(
            conn=self._conn,
            lock=self._lock,
            qualified_name=qualified,
            returning=returning,
            table_schema=input_schema,
        )

        return Stream(output_schema=output_schema, state=state, input_schema=input_schema)

    def delete(self, tx_id: bytes, schema_name: str, table_name: str) -> Stream:
        """Create a delete exchange stream."""
        qualified = f"{schema_name}.{table_name}" if schema_name else table_name

        # Delete receives a batch with row_id column only
        input_schema = pa.schema([("row_id", pa.int64())])
        state = _DeleteState(conn=self._conn, lock=self._lock, qualified_name=qualified)
        return Stream(output_schema=_COUNT_SCHEMA, state=state, input_schema=input_schema)

    def update(self, tx_id: bytes, schema_name: str, table_name: str) -> Stream:
        """Create an update exchange stream."""
        qualified = f"{schema_name}.{table_name}" if schema_name else table_name

        # Update receives row_id + updated columns — schema determined by first batch
        # Use a permissive input schema; actual columns come from the batch
        table_schema = self._table_schema(qualified)
        state = _UpdateState(conn=self._conn, lock=self._lock, qualified_name=qualified)
        return Stream(output_schema=_COUNT_SCHEMA, state=state, input_schema=table_schema)

    # ========== Read (streaming producer) ==========

    def scan(self, tx_id: bytes, schema_name: str, table_name: str, columns: list[str]) -> Stream:
        """Create a scan producer stream."""
        qualified = f"{schema_name}.{table_name}" if schema_name else table_name
        col_list = ", ".join(columns) if columns else "*"

        # Determine output schema
        with self._lock:
            result = self._conn.execute(f"SELECT {col_list} FROM {qualified} LIMIT 0")  # noqa: S608
            output_schema = result.fetch_arrow_table().schema

        state = _ScanState(conn=self._conn, lock=self._lock, qualified_name=qualified, col_list=col_list)
        return Stream(output_schema=output_schema, state=state)

    # ========== DDL ==========

    def execute_ddl(self, sql: str) -> None:
        """Execute DDL statement."""
        with self._lock:
            self._conn.execute(sql)
            logger.debug("DDL executed: %s", sql[:100])

    # ========== Lifecycle ==========

    def ping(self) -> None:
        """Health check."""

    def shutdown(self) -> None:
        """Graceful shutdown."""
        logger.info("Shutdown requested")
        self._conn.close()
        sys.exit(0)


# ============================================================================
# Stream state implementations
# ============================================================================


class _InsertState(ExchangeState):
    """Insert exchange: receives row batches, inserts into table, returns count or RETURNING rows."""

    def __init__(
        self,
        conn: duckdb.DuckDBPyConnection,
        lock: threading.Lock,
        qualified_name: str,
        returning: bool,
        table_schema: pa.Schema,
    ) -> None:
        """Initialize insert state."""
        self.conn = conn
        self.lock = lock
        self.qualified_name = qualified_name
        self.returning = returning
        self.table_schema = table_schema

    def exchange(self, input: AnnotatedBatch, out: OutputCollector, ctx: CallContext) -> None:
        """Insert the input batch and return count or RETURNING rows."""
        batch = input.batch
        col_names = ", ".join(batch.schema.names)
        ret_cols = ", ".join(self.table_schema.names)

        sql = f"INSERT INTO {self.qualified_name} ({col_names}) SELECT * FROM __insert_batch__"  # noqa: S608
        if self.returning:
            sql += f" RETURNING {ret_cols}"

        with self.lock:
            self.conn.register("__insert_batch__", batch)
            result = self.conn.execute(sql)
            if self.returning:
                table = result.fetch_arrow_table()
                self.conn.unregister("__insert_batch__")
                if table.num_rows > 0:
                    out.emit(table.to_batches()[0])
                else:
                    out.emit(pa.record_batch({c: [] for c in self.table_schema.names}, schema=self.table_schema))
            else:
                self.conn.unregister("__insert_batch__")
                out.emit(pa.record_batch({"count": [batch.num_rows]}, schema=_COUNT_SCHEMA))


class _DeleteState(ExchangeState):
    """Delete exchange: receives row_id batches, deletes matching rows."""

    def __init__(self, conn: duckdb.DuckDBPyConnection, lock: threading.Lock, qualified_name: str) -> None:
        """Initialize delete state."""
        self.conn = conn
        self.lock = lock
        self.qualified_name = qualified_name

    def exchange(self, input: AnnotatedBatch, out: OutputCollector, ctx: CallContext) -> None:
        """Delete rows by row_id."""
        batch = input.batch
        with self.lock:
            self.conn.register("__delete_batch__", batch)
            self.conn.execute(
                f"DELETE FROM {self.qualified_name} "  # noqa: S608
                f"WHERE row_id IN (SELECT row_id FROM __delete_batch__)"
            )
            # DuckDB doesn't return rowcount from execute directly; count via changes
            deleted = self.conn.execute("SELECT changes()").fetchone()
            count = deleted[0] if deleted else 0
            self.conn.unregister("__delete_batch__")
        out.emit(pa.record_batch({"count": [count]}, schema=_COUNT_SCHEMA))


class _UpdateState(ExchangeState):
    """Update exchange: receives row_id + updated columns, updates matching rows."""

    def __init__(self, conn: duckdb.DuckDBPyConnection, lock: threading.Lock, qualified_name: str) -> None:
        """Initialize update state."""
        self.conn = conn
        self.lock = lock
        self.qualified_name = qualified_name

    def exchange(self, input: AnnotatedBatch, out: OutputCollector, ctx: CallContext) -> None:
        """Update rows by row_id with new column values."""
        batch = input.batch
        update_cols = [name for name in batch.schema.names if name != "row_id"]
        set_clause = ", ".join(f"{col} = __update_batch__.{col}" for col in update_cols)

        with self.lock:
            self.conn.register("__update_batch__", batch)
            self.conn.execute(
                f"UPDATE {self.qualified_name} SET {set_clause} "  # noqa: S608
                f"FROM __update_batch__ WHERE {self.qualified_name}.row_id = __update_batch__.row_id"
            )
            updated = self.conn.execute("SELECT changes()").fetchone()
            count = updated[0] if updated else 0
            self.conn.unregister("__update_batch__")
        out.emit(pa.record_batch({"count": [count]}, schema=_COUNT_SCHEMA))


class _ScanState(ProducerState):
    """Scan producer: queries all rows from a table and emits them as batches."""

    def __init__(
        self,
        conn: duckdb.DuckDBPyConnection,
        lock: threading.Lock,
        qualified_name: str,
        col_list: str,
    ) -> None:
        """Initialize scan state."""
        self.conn = conn
        self.lock = lock
        self.qualified_name = qualified_name
        self.col_list = col_list
        self._produced = False

    def produce(self, out: OutputCollector, ctx: CallContext) -> None:
        """Produce all rows from the table."""
        if self._produced:
            out.finish()
            return

        self._produced = True
        with self.lock:
            result = self.conn.execute(f"SELECT {self.col_list} FROM {self.qualified_name}")  # noqa: S608
            table = result.fetch_arrow_table()

        for batch in table.to_batches():
            if batch.num_rows > 0:
                out.emit(batch)
        out.finish()


def main() -> None:
    """Entry point for the vgi-transactor command."""
    parser = argparse.ArgumentParser(description="VGI db-transactor server")
    parser.add_argument("--db-path", required=True, help="Path to the DuckDB database file")
    parser.add_argument("--socket", required=True, help="Unix domain socket path to listen on")
    args = parser.parse_args()

    logging.basicConfig(level=logging.INFO, format="%(asctime)s %(name)s %(levelname)s %(message)s")

    impl = TransactorImpl(args.db_path)
    server = RpcServer(TransactorProtocol, impl)
    logger.info("Serving on %s", args.socket)
    serve_unix(server, args.socket, threaded=True)


if __name__ == "__main__":
    main()
