# Copyright 2025, 2026 Query Farm LLC - https://query.farm

"""Generate the reporting reference directly from importable Python contracts.

Run ``python -m vgi.codegen.reporting_docs`` to render to stdout, or use
``scripts/regen_generated.py --only vgi-python`` to update the checked-in pages.
"""

from __future__ import annotations

import inspect
import sys
from collections.abc import Hashable
from types import ModuleType
from typing import Any, TextIO, cast

from vgi_rpc import ArrowSerializableDataclass
from vgi_rpc.rpc import MethodType, rpc_methods

from vgi.reporting import CONTRACT_MODULES, PROTOCOLS, _arrow, _enums
from vgi.reporting._metadata import read_annotation

_TITLES = {
    "common": "Shared records",
    "reports": "Reports",
    "render": "Rendering",
    "schedules": "Schedules",
    "sql_tasks": "SQL tasks",
    "alerts": "Alerts",
    "notify": "Notifications",
    "delegations": "Delegations",
}


def _source(module: ModuleType) -> str:
    """Embed actual module source, so defaults, annotations and docs cannot drift."""
    return inspect.getsource(module).strip() + "\n"


def _method_table(protocol: type[Any]) -> str:
    """Document real vgi-rpc envelopes and explicitly annotated stream row types."""
    lines = [
        "| Method | Arguments | Result / stream row | RPC result envelope | SQL read |",
        "| --- | --- | --- | --- | --- |",
    ]
    tables = set()
    methods = rpc_methods(cast(Hashable, protocol))
    for name, method in methods.items():
        annotation = read_annotation(getattr(protocol, name))
        result: object
        if method.method_type == MethodType.STREAM:
            if annotation is None or annotation.row_type is None:
                raise ValueError(f"{protocol.__name__}.{name} has no declared stream row type")
            result = annotation.row_type
            envelope = "Producer batches"
        else:
            result = method.result_type
            envelope = "`result: binary` (IPC record)"
        if not isinstance(result, type) or not issubclass(result, ArrowSerializableDataclass):
            raise TypeError(f"{protocol.__name__}.{name} has no reporting result dataclass")
        # Materialize every response/stream schema as part of generating the reference.
        _ = result.ARROW_SCHEMA
        arguments = ", ".join(f"`{name}`" for name in method.param_types) or "—"
        read = "—" if annotation is None else "Function"
        if annotation is not None:
            if annotation.table is not None:
                if annotation.table in tables:
                    raise ValueError(f"Duplicate SQL table {protocol.__name__}.{annotation.table}")
                tables.add(annotation.table)
                read += f"; table `{annotation.table}`"
            for fetched in annotation.fetched_columns:
                target = methods[fetched.method]
                request_fields = target.params_schema.names
                for argument, column in fetched.arguments:
                    if argument not in request_fields or column not in result.ARROW_SCHEMA.names:
                        raise ValueError(f"Invalid fetched-column mapping on {protocol.__name__}.{name}")
                target_result = target.result_type
                if fetched.column not in target_result.ARROW_SCHEMA.names:  # type: ignore[attr-defined]
                    raise ValueError(f"Missing fetched column {fetched.column}")
        lines.append(f"| `{name}` | {arguments} | `{result.__name__}` | {envelope} | {read} |")
    return "\n".join(lines) + "\n"


def targets() -> list[tuple[str, str]]:
    """Declare the index and independently reviewable reference pages."""
    root = "docs/design/reporting-protocols"
    return [("index", f"{root}/python-contracts.md")] + [(name, f"{root}/reference/{name}.md") for name in _TITLES]


def render(record: str = "index") -> str:
    """Render one deterministic page from the authoritative Python source."""
    generated = "<!-- Generated by vgi.codegen.reporting_docs; edit vgi/reporting/*.py. -->\n"
    if record == "index":
        parts = [
            "# Python reporting contracts\n",
            generated,
            "The importable definitions live in `vgi/reporting/`. Each protocol has its own "
            "source module and generated reference page. Service implementations and the SQL "
            "adapter remain separate work.\n",
            "Methods take direct named arguments, with dataclasses for structured values such as "
            "report envelopes, schedules and notifications. Scalar arguments are individual RPC "
            "columns; dataclass arguments and unary dataclass results use the framework's binary "
            "IPC encoding. Producer row schemas and safe SQL reads are explicit annotations.\n",
            "| Reference | Python source |\n| --- | --- |",
        ]
        parts.extend(
            f"| [{title}](reference/{name}.md) | `vgi/reporting/{name}.py` |" for name, title in _TITLES.items()
        )
        parts.append(
            "\nSee [wire behavior](wire-contracts.md) for lifecycle, errors, encoding rules and "
            "worker policy. Regenerate these pages with "
            "`uv run python scripts/regen_generated.py --only vgi-python`.\n"
        )
        return "\n".join(parts)

    title = _TITLES[record]
    module = next(m for m in CONTRACT_MODULES if m.__name__.rsplit(".", 1)[-1] == record)
    parts = [
        f"# {title}: Python reference\n",
        generated,
        "[All protocols](../python-contracts.md) · [Wire behavior](../wire-contracts.md)\n",
        f"Source: `vgi/reporting/{record}.py`. Edit the Python module and regenerate this page.\n",
    ]
    if record == "common":
        parts.extend(
            [
                "## Arrow aliases and string choices\n",
                f"```python\n{_source(_arrow)}```\n",
                f"```python\n{_source(_enums)}```\n",
            ]
        )
    else:
        spec = "credentials" if record == "delegations" else record
        parts.append(f"[Behavior specification](../{spec}.md) · [Shared records](common.md)\n")
        protocol = next(p for p in PROTOCOLS if p.__module__ == module.__name__)
        parts.append(f"Protocol `{protocol.protocol_name}`, version `{protocol.protocol_version}`.\n")
        parts.append("## Methods\n")
        parts.append(_method_table(protocol))
    parts.append("## Python definitions\n")
    parts.append(f"```python\n{_source(module)}```\n")
    return "\n".join(parts)


def emit(out: TextIO, *, record: str = "index") -> None:
    """Write one generated reference page to a text stream."""
    out.write(render(record))


if __name__ == "__main__":
    emit(sys.stdout)
